 - name: Install Go Langauge
   apt: pkg=golang state=present
   when: ansible_distribution == "Ubuntu"

 - name: Install Go OSX
   homebrew: pkg=go state=present
   when: ansible_distribution == "MacOSX"
   become: false 

