---
- hosts: localhost
  become: true

  roles:
   - { role: ohmyzsh, tags: ohmyzsh }
   - { role: powerline_fonts, tags: [powerline, ohmyzsh] }            
   - { role: vim-gnome, tags: [vim-gnome, go] }
   - { role: golang, tags: [golang, go] }
   - { role: terminator, tags: terminator }
   - { role: docker, tags: docker }
