 - name: "Install VIM Gnome - This has all prebuilt extensions"
   apt: pkg=vim-gnome state=present
 
 - name: Install Vundle plugin manager
   git: clone=yes repo=https://github.com/VundleVim/Vundle.vim.git dest="{{local_home|default('~/')}}/.vim/bundle/Vundle.vim" accept_hostkey=yes update=no
 
 - name: "Remove any old .vimrc"
   file: path={{local_home|default('~/')}}/.vimrc state=absent 
 
 - name: Install custom .vimrc
   template: src=../files/vimrc.j2 dest="{{local_home|default('~/')}}/.vimrc"
 
 - name: Install all plugin's with Vundle
   shell: "vim +PluginInstall +qall"
 
 - name: Check if Vim-Go Is Installed
   stat: path="{{local_home|default('~/')}}/.vim/bundle/vim-go/plugin/go.vim"
   register: govim_installed   
           
# - debug: var="{{govim_installed}}"

 - name: Install Go Lang if Vim-Go plugin is installed
   include: "{{ playbook_dir }}/roles/golang/tasks/main.yml"
   when: govim_installed.stat.exists

 - name: Install Go tools for vim-go
   shell: vim +GoBinariesInstall +qall
   when: govim_installed.stat.exists

 - name: Check if YouCompleteMe plugin is installed
   stat: path="{{local_home|default('~/')}}/.vim/bundle/YouCompleteMe/plugin/youcompleteme.vim"
   register: ycm_installed

 - name: Install required library's for building YCM's autocomplete
   apt: pkg="{{item}}" state=present
   with_items:
        - build-essential
        - python-dev
        - cmake
   when: ycm_installed.stat.exists

 - name: Check if YCM has already been built
   stat: path="{{local_home|default('~/')}}/.vim/bundle/YouCompleteMe/third_party/ycmd/ycm_core.so"
   register: ycm_compiled

 - name: Compile and Install YCM autocomplete with Go support
   shell: "{{local_home|default('~/')}}/.vim/bundle/YouCompleteMe/install.py --gocode-completer"
   when: ycm_compiled.stat.exists != true 
