 - name: Install Docker Repo Key
   apt_key: keyserver=hkp://pgp.mit.edu:80 id={{docker_repo_key_id}}
 
 - name: Install Docker source list
   template: src=../files/docker.list dest=/etc/apt/sources.list.d/docker.list
 
 - name: Update Apt
   apt: update_cache=yes

 - name: Install Docker
   apt: pkg=docker-engine state=present
